#!/usr/bin/bash

# Funcion "operations" para packer
# By Kevin .J Figueroa : 2023-01-13

opcion=0
source ~/.scripts/functions/out
source ~/.scripts/functions/del

zipf (){
    sleep 1
    echo -e "\n"
    if [ -d zippack ]
        then
            echo -e "\tAl parecer ya existe un directorio con el nombre de \"${rf}zippack${noc}.\"\n\tPor favor, revisa si ya existen los archivos esperados."; sleep 1; out
        else
            mkdir -p zippack && $(cd zippack && zip pack.zip ../* 1> output.log) 2>/dev/null
            echo -e -n "\t...Podras encontrar el ${r}.ZIP${noc} en el nuevo directorio: ${rf}$(ls |grep 'zippack')${noc}\n"; sleep 1; del
    fi
}

uzipf (){
	sleep 1
	echo -e "\n"
	if [ -d unpacked ]
	then
            echo -e "\tAl parecer ya existe un directorio con el nombre de \"${rf}unpacked${noc}.\"\n\tPor favor, revisa si ya existen los archivos esperados."; sleep 1; out
        else
		mkdir -p unpacked && unzip *.zip -d unpacked 2> unpacked/error.log 1> unpacked/out.log
		echo -e -n "\t...Podras encontrar el ${r}.ZIP${noc} en el nuevo directorio: ${rf}$(ls |grep 'unpacked')${noc}\n"; sleep 1; out
	 fi
}

echo -e "\n";read -e -n1 -p "   Seleccione entre $(echo -e "${am}[1-3]${noc}: ")" opcion

    case $opcion in
        1)
            zipf;
            ;;
        2) 
            uzipf;
            ;;
        3)  
            out;
            ;;
    esac
