#!/usr/bin/bash

# Funcion "out" para packer
# By Kevin .J Figueroa : 2023-01-13

opcion=0

out (){
    echo -e "\n\tSaliendo del Programa."; sleep 1;
    if [ -d zippack ] || [ -d unpacked ]
        then
		echo -e "\n\tDirectorios existentes: ${az}$(ls |grep 'zippack') ${az}$(ls |grep 'unpacked')${noc}";echo -e "\n"
		sleep 1; echo -e "\t...Bye!\n"
    else
		echo -e "\n\tNo se ha creado ningun directorio."
		sleep 1; echo -e "\t...Bye!\n"
    fi
    exit 0
}
