#!/usr/bin/bash

# Make as many sample files as you want.
# By Kevin .J Figueroa : 2023-01-13

read -p "how many sample files do you like? - (put a number) " last

for num in `seq $last`
    do
    touch file_$num
    echo -e "\nesto es un numero random: $(( ($RANDOM * $RANDOM)**15 ))\n" > file_$num
    done

exit 0
