#!/usr/bin/bash

# Main script.
# By Kevin .J Figueroa : 2023-01-13

r="\e[31m"
rf="\e[1;31m"
am="\e[33m"
az="\e[1;34m"
noc="\e[0m"
inv0="\e[0;7m"
inv1="\e[1;7m" 


function selector (){
    #subprocess
    source ~/.scripts/functions/op
}

opcion=0
clear

echo -e "░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ "
echo -e "░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒"
echo -e "░▒${inv0}                                                  ${noc}"
echo -e "░▒${inv1}                    PACKER                        ${noc}"
echo -e "░▒${inv0}                                                  ${noc}"
echo -e "░▒${inv0}       Correr en un directorio para empaquetar    ${noc}"
echo -e "░▒${inv0}             todo en un archivo .ZIP.             ${noc}"
echo -e "░▒${inv0}      O bien, correr en un directorio para        ${noc}"
echo -e "░▒${inv0}   desempaquetar un archivo comprimido en ZIP.    ${noc}"
echo -e "░▒${inv0}                                                  ${noc}"
echo -e "░▒${inv1}                                                  ${noc}"
#echo -e "\n"

while :
do
    echo -e "░▒${inv0}                                                  ${noc}"
    echo -e "░▒${inv0}  1. ZIP                                          ${noc}"
    echo -e "░▒${inv0}  2. unZIP                                        ${noc}"
    echo -e "░▒${inv0}  3. Salir                                        ${noc}"
    echo -e "░▒${inv1}                                                  ${noc}"
    echo -e "░▒${inv1}                                                  ${noc}"
    echo -e " ▒${inv1}                Kevin J. Figueroa                 ${noc}"
    echo -e "  ${inv1}                      2023                        ${noc}"
    echo -e "  ${inv1}                                                  ${noc}"
    selector
done
